<?php

/**
 * BaseAccountType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $global_id
 * @property string $name
 * @property string $description
 * @property blob $icon
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $AccountType
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getGlobalId()    Returns the current record's "global_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method blob                getIcon()        Returns the current record's "icon" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getAccountType() Returns the current record's "AccountType" collection
 * @method AccountType         setId()          Sets the current record's "id" value
 * @method AccountType         setGlobalId()    Sets the current record's "global_id" value
 * @method AccountType         setName()        Sets the current record's "name" value
 * @method AccountType         setDescription() Sets the current record's "description" value
 * @method AccountType         setIcon()        Sets the current record's "icon" value
 * @method AccountType         setCreatedAt()   Sets the current record's "created_at" value
 * @method AccountType         setUpdatedAt()   Sets the current record's "updated_at" value
 * @method AccountType         setAccountType() Sets the current record's "AccountType" collection
 * 
 * @package    rutino-server
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAccountType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('account_type');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('global_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('icon', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Account as AccountType', array(
             'local' => 'id',
             'foreign' => 'account_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}