DROP TABLE 
report,
periodic_transaction,
transaction,
account,
wallet,
account_type,
currency,
sf_guard_forgot_password,
sf_guard_remember_key,
sf_guard_user_group,
sf_guard_user_permission,
sf_guard_group_permission,
sf_guard_permission,
sf_guard_group,
sf_guard_user;