<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/26 22:48:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rutino-server',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
