<?php

/**
 * PeriodicTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeriodicTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeriodicTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PeriodicTransaction');
    }
}