<?php

/**
 * userdataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class userdataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object userdataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('userdata');
    }
}