<?php

/**
 * WalletTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WalletTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WalletTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Wallet');
    }
}