all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=rutino_server'
      username: root
      password:
      # dsn:        mysql:dbname=yppwwvxi_rutino_server;host=localhost
      # username:   yppwwvxi_rutino
      # password:   langostin0s